# Generated by Django 4.0.7 on 2022-09-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1025_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperlesstask",
            name="attempted_task",
        ),
    ]
